docs: translate « static analysis » from `en` to `fr`
Exodus-Privacy/website pull request #110
Opened 2020-10-06 11:28 UTC by MKlblangenois

2020-10-07 12:32 UTC, Gu1nness requested changes

2020-10-07 12:32 UTC, Gu1nness commented on content/post/exodus_static_analysis.fr.md
> +L'analyse statique des applications Android est au cœur de la plateforme εxodus. L'idée principale est de détecter la présence de _trackers_ connus dans une application sans l'exécuter. En fait, εxod
We use the word «pisteurs» instead of «trackers» in French

2020-10-07 12:34 UTC, Gu1nness commented on content/post/exodus_static_analysis.fr.md
> +εxodus "fouille" dans les fichiers `.apk` pour trouver des _trackers_ et ces _trackers_ peuvent être identifiés par leur propre espace de nom. Par exemple, le `name-space/package` racine de la biblio
Here as well, «pisteurs» please :)

2020-10-07 12:35 UTC, Gu1nness commented on content/post/exodus_static_analysis.fr.md
> +Ainsi, lorsque vous [soumettez](https://reports.exodus-privacy.eu.org/analysis/submit/) une application pour analyse, εxodus la télécharge depuis Google Play, extrait le fichier `.apk`, appelle `dexd
Here as well, «pisteurs» please :)

2020-10-07 12:35 UTC, Gu1nness commented on content/post/exodus_static_analysis.fr.md
> +Si vous souhaitez nous aider à améliorer la base de connaissances εxodus, [contactez-nous](/fr/page/who/) et demandez un compte [ETIP](http://etip.exodus-privacy.eu.org/). ETIP est une plateforme col
Here as well, «pisteurs» please :)

2020-10-07 12:35 UTC, Gu1nness commented on content/post/exodus_static_analysis.fr.md
> +Si vous êtes développeur d'applications, vous pouvez utiliser [exodus-standalone](https://github.com/Exodus-Privacy/exodus-standalone) pour analyser votre application avant sa publication sur Google
Please put «avant» surrounded by \*\* :)

2020-10-08 06:48 UTC, MKlblangenois commented
@Gu1nness I've updated the article based on your changes request 😊

2020-10-08 15:00 UTC, Gu1nness approved these changes
LGTM

2020-10-14 06:41 UTC, pnu-s requested changes

2020-10-14 06:41 UTC, pnu-s commented on content/post/exodus_static_analysis.fr.md
> +Cette sortie n'est pas vraiment conviviale mais pour chaque classe déclarée dans l'application, nous avons un `Class # x` et un `Class descriptor`. Le descripteur de classe est la représentation JVM
```suggestion
Cette sortie n'est pas vraiment lisible mais pour chaque classe déclarée dans l'application, nous avons un `Class # x` et un `Class descriptor`. Le descripteur de classe est la représentation JVM des espaces de nom d'application (nom de classe complet). Dans cet exemple, `Classe # 0` est `android.databinding.Observable` avec `android.databinding` le nom du package et `Observable` le nom de la classe déclarée.
```

2020-10-14 06:41 UTC, pnu-s commented on content/post/exodus_static_analysis.fr.md
> +L'analyse statique des applications Android est au cœur de la plateforme εxodus. L'idée principale est de détecter la présence de pisteurs connus dans une application sans l'exécuter. En fait, εxodus
```suggestion
L'analyse statique des applications Android est au cœur de la plateforme εxodus. L'idée principale est de détecter la présence de pisteurs connus dans une application sans l'exécuter. En effet, εxodus ne peut pas prendre trop de temps pour chaque analyse, donc la méthode de détection doit être efficace dans le temps, reproductible et exempte de faux positifs.
```

2020-10-14 06:41 UTC, pnu-s commented on content/post/exodus_static_analysis.fr.md
> +εxodus "fouille" dans les fichiers `.apk` pour trouver des pisteurs et ces pisteurs peuvent être identifiés par leur propre espace de nom. Par exemple, le `name-space/package` racine de la bibliothèq
```suggestion
εxodus "fouille" dans les fichiers `.apk` pour trouver des pisteurs et ces pisteurs peuvent être identifiés par leur propre espace de nom. Par exemple, le `espace-de-nom/packet` racine de la bibliothèque Amazon Ads est `com.amazon.device.ads`, cette bibliothèque partage le nom du package `com.amazon` avec d'autres bibliothèques Amazon. Ainsi, à ce stade, une signature de pisteurs est un espace de nom (un nom de _package_).
```

2020-10-14 06:41 UTC, pnu-s commented on content/post/exodus_static_analysis.fr.md
> +Pour le moment, εxodus connaît [152 pisteurs](https://reports.exodus-privacy.eu.org/trackers/), et si nous regardons [Flurry](https://reports.exodus-privacy.eu.org/trackers/25/), nous avons la règle
```suggestion
Pour le moment, εxodus connaît [152 pisteurs](https://reports.exodus-privacy.eu.org/trackers/), et si nous regardons [Flurry](https://reports.exodus-privacy.eu.org/trackers/25/), nous avons la règle de détection `com.flurry.` qui est une [regex](https://fr.wikipedia.org/wiki/Expression_r%C3%A9guli%C3%A8re).
```

2020-10-14 06:41 UTC, pnu-s commented on content/post/exodus_static_analysis.fr.md
> +{{< fig src="/media/flurry.png" caption="Aperçu de la description Flurry" >}}
```suggestion
{{< fig src="/media/flurry.png" caption="Aperçu de la description du pisteur Flurry" >}}
```

2020-10-14 06:41 UTC, pnu-s commented on content/post/exodus_static_analysis.fr.md
> +Ainsi, utilisons `grep` pour voir si `my.apk` contient les classes de Flurry :
```suggestion
Maintenant, utilisons `grep` pour voir si `my.apk` contient les classes de Flurry :
```

2020-10-14 06:41 UTC, pnu-s commented on content/post/exodus_static_analysis.fr.md
> +Si vous êtes développeur d'applications, vous pouvez utiliser [exodus-standalone](https://github.com/Exodus-Privacy/exodus-standalone) pour analyser votre application **avant** sa publication sur Goo
```suggestion
Si vous êtes développeur·euse d'applications, vous pouvez utiliser [exodus-standalone](https://github.com/Exodus-Privacy/exodus-standalone) pour analyser votre application **avant** sa publication sur Google Play.
```

2020-10-14 06:42 UTC, pnu-s commented
Hi @MKlblangenois and thanks for the proposal!
I finally had the time to review it and I made a couple of suggestions :)

2020-10-16 09:21 UTC, Gu1nness approved these changes

2020-10-16 19:58 UTC, merged

2020-10-16 19:58 UTC, pnu-s commented
Thanks again @MKlblangenois :tada: