adding the logos of Afnic foundation and defensive lab agency
Exodus-Privacy/website pull request #115
Opened 2020-12-04 11:25 UTC by MeTaLPoU

2020-12-04 11:43 UTC, codeurimpulsif requested changes
DLA logo is ok but the AFNIC one is small, maybe we need to resize the image to reduce blank space in it.

2020-12-06 11:32 UTC, pnu-s requested changes

2020-12-06 11:32 UTC, pnu-s commented on content/page/supporters.en.md
> +                <h6 class="card-title">Fondation Afnic pour la solidarité numérique</h6>
```suggestion
                <h6 class="card-title">AFNIC foundation</h6>
```

2020-12-06 11:32 UTC, pnu-s commented on content/page/supporters.fr.md
> +                <h6 class="card-title">Fondation Afnic pour la solidarité numérique</h6>
```suggestion
                <h6 class="card-title">Fondation AFNIC</h6>
```

2020-12-10 20:03 UTC, codeurimpulsif approved these changes
I think we can merge this :smiley:

2020-12-10 20:09 UTC, pnu-s approved these changes

2020-12-10 20:09 UTC, merged