Add scientist category to press page (Issue #159)
Exodus-Privacy/website pull request #160
Opened 2022-05-01 18:52 UTC by jfoucry

Add ## Scientist publications in French; Scientist publication in English; Publications scientifique francophone ; Publications scientifique anglophone in pages `press.fr.md` and `press.en.md`, with *INRIA* publication about video games on smartphone.

2022-05-01 20:31 UTC, DavidLibeau commented on content/page/press.en.md
> +## Scientist publications in French
Je mettrais plus "Scientific publication" (c.f. https://www.sciencedirect.com/topics/social-sciences/scientific-publications)

2022-05-02 05:55 UTC, jfoucry commented on content/page/press.en.md
> +## Scientist publications in French
C'est ce que je voulais mettre mais je me suis basé sur le titre de l'issue.

2022-05-07 09:08 UTC, pnu-s requested changes
Thanks for the PR!

Made a couple of suggestions

2022-05-07 09:08 UTC, pnu-s commented on content/page/press.en.md
> +
```suggestion
```

2022-05-07 09:08 UTC, pnu-s commented on content/page/press.en.md
> +
```suggestion
```

2022-05-07 09:08 UTC, pnu-s commented on content/page/press.en.md
> +* **INRIA** — *Apr 25 2022* — [The price to play](https://dl.acm.org/doi/abs/10.1145/3485447.3512279)
```suggestion
* **INRIA** - *Apr 25 2022* - [The price to play](https://dl.acm.org/doi/abs/10.1145/3485447.3512279)
```

2022-05-07 09:08 UTC, pnu-s commented on content/page/press.en.md
> +* **INRIA** — *Apr 25 2022* — [Jeux vidéo sur mobile : protéger la vie pvivée en ligne](https://www.inria.fr/fr/jeux-video-smartphones-securite-donnees-personnelles-internet)
```suggestion
* **INRIA** - *Apr 25 2022* - [Jeux vidéo sur mobile : protéger la vie pvivée en ligne](https://www.inria.fr/fr/jeux-video-smartphones-securite-donnees-personnelles-internet)
```

2022-05-07 09:08 UTC, pnu-s commented on content/page/press.fr.md
> +## Parutions Scientifiques Francophone
```suggestion
## Parutions scientifiques francophones
```

2022-05-07 09:08 UTC, pnu-s commented on content/page/press.fr.md
> +* **INRIA** — *25 avr 2022* — [Jeux vidéo sur mobile : protéger la vie privée en ligne](https://www.inria.fr/fr/jeux-video-smartphones-securite-donnees-personnelles-internet)
```suggestion
* **INRIA** - *25 Avr 2022* - [Jeux vidéo sur mobile : protéger la vie privée en ligne](https://www.inria.fr/fr/jeux-video-smartphones-securite-donnees-personnelles-internet)
```

2022-05-07 09:08 UTC, pnu-s commented on content/page/press.fr.md
> +## Parutions Scientifiques anglophone
```suggestion
## Parutions scientifiques anglophones
```

2022-05-07 09:08 UTC, pnu-s commented on content/page/press.fr.md
> +* **INRIA** – *25 apr 2022* – [The price to play](https://dl.acm.org/doi/abs/10.1145/3485447.3512279)
```suggestion
* **INRIA** - *25 Avr 2022* - [The price to play](https://dl.acm.org/doi/abs/10.1145/3485447.3512279)
```

2022-05-15 06:54 UTC, jfoucry commented on content/page/press.en.md
> +
Those are missing?

2022-05-21 11:51 UTC, pnu-s approved these changes

2022-05-21 11:51 UTC, pnu-s commented
Fixes #159

2022-05-21 11:52 UTC, merged